# Bab 8 Backpropagation (1)

## Praktikum

### a) Fungsi *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [ ]:
def bin_enc(lbl):
  mi = min(lbl)
  length = len(bin(max(lbl) - mi + 1)[2:])
  enc = []

  for i in lbl:
    b = bin(i - mi)[2:].zfill(length)

    enc.append([int(n) for n in b])
  return enc

def bin_dec(enc, mi=0):
  lbl = []

  for e in enc:
    rounded = [int(round(x)) for x in e]
    string = ''.join(str(x) for x in rounded)
    num = int(string, 2) + mi

    lbl.append(num)

  return lbl

### b) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [ ]:
labels = 1, 2, 3, 4
enc = bin_enc(labels)
dec = bin_dec(enc, min(labels))

print(enc)
print(dec)

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 1]]
[1, 2, 3, 4]


### c) Fungsi *One-hot Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:


In [ ]:
import numpy as np

def onehot_enc(lbl, min_val=0):
  mi = min(lbl)
  enc = np.full((len(lbl), max(lbl) - mi + 1), min_val, np.int8)

  for i, x in enumerate(lbl):
    enc[i, x - mi] = 1

  return enc

def onehot_dec(enc, mi=0):
  return [np.argmax(e) + mi for e in enc]

### d) Percobaan *Binary Encoding* dan *Decoding*

Tulis kode ke dalam *cell* di bawah ini:

In [ ]:
labels = 1, 2, 3, 4
enc = onehot_enc(labels)
dec = onehot_dec(enc, min(labels))

print(enc)
print(dec)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[1, 2, 3, 4]


### e) Fungsi Aktivasi Sigmoid dan Derivatifnya

Tulis kode ke dalam *cell* di bawah ini:

In [ ]:
def sig(X):
  return [1 / (1 + np.exp(-x)) for x in X]

def sigd(X):
  output = []

  for i, x in enumerate(X):
    s = sig([x])[0]

    output.append(s * (1 - s))

  return output

# **Tugas Praktikum** #

**2. Membaca Kolom Terakhir dari CSV**

In [ ]:
import pandas as pd
from google.colab import files

# Unggah file CSV
uploaded = files.upload()

# Baca file CSV
for file_name in uploaded.keys():
    data = pd.read_csv(file_name)

# Membuat variabel kelas
kelas = data.iloc[:, -1].astype(str).tolist()  # Ambil kolom terakhir dan ubah ke list of string
print(kelas)

Saving iris_csv.csv to iris_csv.csv
['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor', 'Iri

**3. Binary Encoding dan Decoding**

In [ ]:
# Fungsi binary encoding
def bin_enc_str(string_list):
    unique_strings = list(set(string_list))
    bin_encoded = []

    for item in string_list:
        idx = unique_strings.index(item)
        bin_str = format(idx, f'0{len(unique_strings).bit_length()}b')
        bin_encoded.append([int(bit) for bit in bin_str])

    return bin_encoded, unique_strings

# Fungsi binary decoding
def bin_dec_str(bin_encoded, unique_strings):
    decoded = []

    for bin_code in bin_encoded:
        idx = int("".join(map(str, bin_code)), 2)
        decoded.append(unique_strings[idx])

    return decoded

bin_encoded, unique_strings = bin_enc_str(kelas)
print("Binary Encoded:", bin_encoded)
print("Decoded:", bin_dec_str(bin_encoded, unique_strings))

Binary Encoded: [[1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [1, 0], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 1], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],

**4. One-Hot Encoding dan Decoding**

In [ ]:
import numpy as np

# Fungsi one-hot encoding
def onehot_enc_str(string_list):
    unique_strings = list(set(string_list))
    onehot_encoded = []

    for item in string_list:
        onehot = [0] * len(unique_strings)
        onehot[unique_strings.index(item)] = 1
        onehot_encoded.append(onehot)

    return onehot_encoded, unique_strings

# Fungsi one-hot decoding
def onehot_dec_str(onehot_encoded, unique_strings):
    decoded = []

    for onehot in onehot_encoded:
        idx = np.argmax(onehot)
        decoded.append(unique_strings[idx])

    return decoded

onehot_encoded, unique_strings = onehot_enc_str(kelas)
print("One-Hot Encoded:", onehot_encoded)
print("Decoded:", onehot_dec_str(onehot_encoded, unique_strings))

One-Hot Encoded: [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0, 1, 0], [0,